// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user

import (
	"go-basic-gqlgen/ent/schema/ulid"
)

// Define an input type for the mutation below.
// https://graphql.org/learn/schema/#input-types
type FollowUserInput struct {
	// ID of the following User
	UserID ulid.ID `json:"userID"`
	// ID of Followed User
	FollowUserID ulid.ID `json:"followUserID"`
}

type GroupUserInput struct {
	// ID of the following User
	UserID ulid.ID `json:"userID"`
	// ID of Followed User
	GroupID ulid.ID `json:"groupID"`
}
