// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user

import (
	"go-basic-gqlgen/ent/schema/ulid"
)

type GroupUserInput struct {
	// ID of the following User
	UserID ulid.ID `json:"userID"`
	// ID of Followed User
	GroupID ulid.ID `json:"groupID"`
}
