// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (e *EmployeeQuery) CollectFields(ctx context.Context, satisfies ...string) *EmployeeQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		e = e.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return e
}

func (e *EmployeeQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *EmployeeQuery {
	return e
}
