// Code generated by entc, DO NOT EDIT.

package ent

import (
	"go-basic-gqlgen/ent/employee"
	"go-basic-gqlgen/ent/schema"
	"go-basic-gqlgen/ent/schema/ulid"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescCreatedAt is the schema descriptor for created_at field.
	employeeDescCreatedAt := employeeFields[3].Descriptor()
	// employee.DefaultCreatedAt holds the default value on creation for the created_at field.
	employee.DefaultCreatedAt = employeeDescCreatedAt.Default.(time.Time)
	// employeeDescUpdatedAt is the schema descriptor for updated_at field.
	employeeDescUpdatedAt := employeeFields[4].Descriptor()
	// employee.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employee.DefaultUpdatedAt = employeeDescUpdatedAt.Default.(time.Time)
	// employeeDescID is the schema descriptor for id field.
	employeeDescID := employeeFields[0].Descriptor()
	// employee.DefaultID holds the default value on creation for the id field.
	employee.DefaultID = employeeDescID.Default.(func() ulid.ID)
}
