// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
